!(function(){function e(e){if(!window.Deruga||!window.Deruga.useLocalStorage)
    return(function e(t){for(var n=t+"=",o=document.cookie.split(";"),r=0;r<o.length;r++){var i=o[r].trim();if(0===i.indexOf(n))return decodeURIComponent(i.substring(n.length,i.length));}
    return null})(e);try{var t=localStorage.getItem(e);if(!t)return null;var n=JSON.parse(t);if(!n)return null;if(Date.now()>n.exp)return localStorage.removeItem(e),null;return n.val}catch(o){return null}}
    function t(e){var t=Date.now(),n="DerugaPop_",o=encodeURIComponent(e||"/"),r=0;if(window.Deruga&&window.Deruga.useLocalStorage)
    for(var i=0;i<localStorage.length;i++){var p=localStorage.key(i);if(0===p.indexOf(n)&&p.endsWith("::"+o)){var a=localStorage.getItem(p);if(a)
    try{var s=JSON.parse(a);s&&t<s.exp?r++:localStorage.removeItem(p)}catch(u){}}}else for(var c=document.cookie.split(";"),h=0;h<c.length;h++){var l=c[h].trim();if(0===l.indexOf(n)){var f=l.indexOf("=");if(-1===f)continue;var d=l.substring(0,f),m=decodeURIComponent(l.substring(f+1));if(d.endsWith("::"+o)){var v=parseInt(m,10);!isNaN(v)&&t<v&&r++}}}
    return r}
    var n={cap:null,settings:{},urls:[],minipopmon:!1,lastPop:0,retriesLastPop:0,popSlots:0,useLocalStorage:!1,_testCookie:function(){try{var e="testcookie_"+Math.floor(1e4*Math.random());if(((document.cookie=e+"=1; path=/"),-1!==document.cookie.indexOf(e+"=")))return(document.cookie=e+"=; path=/; expires=Thu, 01 Jan 1970 00:00:01 GMT"),!0}catch(t){}
    return!1},reset:function(){this.urls=[]},add:function(e,t){var n=t||{};n.type?this.cap&&this.cap.env&&"chrome"===this.cap.env.b&&(n.type="popup"):(this.cap&&this.cap.env&&"chrome"===this.cap.env.b?(n.type="popup"):this.cap&&this.cap.popunder&&n.under&&"chrome"!==this.cap.env.b?(n.type="popunder"):(n.type="popup"),n.forceunder&&this.cap&&this.cap.popunder&&"chrome"!==this.cap.env.b&&(n.type="popunder")),n.newTab&&(n.type="tabup"),this.preload(e),this.popSlots++,this.addUrl(e,n)},config:function(e){e&&"number"==typeof e.delay&&(this.settings.delay=e.delay)},checkStackEmpty:function(){for(var e=0;e<this.urls.length;e++){var t=this.urls[e];if((t.options||(t.options={}),"function"!=typeof t.options.shouldFire||t.options.shouldFire()))return!1}
    return!0},checkStack:function(){for(var e=0;e<this.urls.length;e++){var n=this.urls[e];if((n.options||(n.options={}),"function"!=typeof n.options.shouldFire||n.options.shouldFire())){if(!(t(n.options.cookiePath||"/")>=this.popSlots)&&n._lastOpen!==this._clickId)return(n._lastOpen=this._clickId),n}}
    return!1},preload:function(e){try{var t=document.createElement("link");(t.rel="dns-prefetch"),(t.href=e),document.head.appendChild(t);var n=document.createElement("link");(n.rel="preconnect"),(n.href=e),document.head.appendChild(n)}catch(o){}},_windowOpen:function(e,t){var n,o=String(Math.random());var openFunc=window["op"+"en"];this.cap&&this.cap.env&&"msie"===this.cap.env.b&&this.cap.env.v<=9&&(o=""),(n=t?openFunc("",o,t):openFunc("",o));try{n.location.replace(e)}catch(r){}
    return n},_openTabup:function(e){return this._windowOpen(e)},_openTabunder:function(e){if(this.cap&&!1===this.cap.tabunder)return this._openTabup(e);var t=this._openTabup(document.location.href),n=this;return((this.ti=setInterval(function(){if(t)
    try{document.location.replace(e)}catch(o){clearInterval(n.ti)}},10)),t)},_getOptString:function(){var e,t,n,o,r,i,p=((e=0.97),(t=0.95),(n=window.screen.availWidth||window.screen.width||window.outerWidth||1024),(o=window.screen.availHeight||window.screen.height||window.outerHeight||768),(r=Math.floor((Math.random()*(1-e)+e)*n)),{w:r,h:(i=Math.floor((Math.random()*(1-t)+t)*o)),l:Math.max(Math.floor(Math.random()*(n-r)),0),t:Math.max(Math.floor(Math.random()*(o-i)*0.4),0)});return"top="+p.t+",left="+p.l+",width="+p.w+",height="+p.h+",status=0,location=1,toolbar=1,menubar=1,resizable=1,scrollbars=1"},_openPopup:function(e){return this._windowOpen(e,this._getOptString())},_openPopunderSafari:function(e){function t(e,t,n){var o=document.createElement("iframe");(o.style="display:none;"),document.body.appendChild(o);var r=o.contentWindow.document.createElement("script");(r.type="text/javascript"),(r.innerHTML="window.parent = window.top = window.frameElement = null;window.mkp = function(url, name, opts) {var popWin = window.open(url, name, opts);try { popWin.opener = null; } catch(e) {}return popWin;};"),o.contentWindow.document.body.appendChild(r);var i=o.contentWindow.mkp(e,t,n);return document.body.removeChild(o),i}
    window.name=String(Math.random());var n=t(e,String(Math.random()),this._getOptString());return t("",window.name,""),(window.name=null),n},_openPopunderBlur:function(e){var t=this._openPopup(e);try{document.focus()}catch(n){}
    return window.focus(),t.blur(),t},_openPopunderFF:function(e){var t=this;return(setTimeout(function(){var n=t._openPopup(e);"about:blank"===e&&(t.prepop=n)},0),setTimeout(function(){var e=window.open("","_self");e&&!e.closed&&e.focus()},0),!0)},_openPopunderIE11:function(e){var t=this;return((this.tw=this._openPopup(e)),this.focusInterval&&clearInterval(this.focusInterval),(this.runs=0),(this.focusInterval=setInterval(function(){try{t.tw&&(t.tw.blur(),t.tw.opener.focus(),window.self.focus(),window.focus(),document.focus())}catch(e){}
    t.runs++,t.runs>10&&t.focusInterval&&clearInterval(t.focusInterval)},100)),this.tw)},_openPopunderCRPre:function(){},_openPopunderCRPost:function(e){this.prepop&&"ready"===this.prepop.name?this.prepop.location.replace(e):this.prepop&&(this.prepop.name=e)},_getMinipopStatus:function(e){if(!e||e.closed||!e.location)return"closed";try{var t=e.name;if(""===t)return"waiting";if("ready"===t)return"prepopready"}catch(n){return"success"}
    return 0},_openPopunderCR:function(e,t){if(this.cap&&this.cap.env){var n=this.cap.env;if("desktop"!==n.f)return this.cap.tabunder?this._openTabunder(e):this._openTabup(e);if("chrome"===n.b)return(this.minipopmon=!0),this._openPopunderCRPre(t);if("firefox"===n.b)return this._openPopunderFF(e);if("msie"===n.b&&n.v<11)return this._openPopunderBlur(e);if("msie"===n.b&&11===n.v)return this._openPopunderIE11(e);if("safari"===n.b)return this._openPopunderSafari(e);if("edge"===n.b)return this.cap.tabunder?this._openTabunder(e):this._openPopup(e);}},_prepopOpen:function(){},_prepopReady:function(){return!!(this.prepop&&!this.prepop.closed&&this.prepop.location)},_prepopUse:function(e){this.settings.onbeforeopen&&(e=this.settings.onbeforeopen(e));try{"chrome"===this.cap.env.b?(this._openPopunderCRPost(e),(this.prepop=!1)):(this.prepop.location.replace(e),(this.prepop=!1))}catch(t){return!1}
    return!0},_prepopClose:function(){try{this.prepop.close()}catch(e){return!1}
    return!0},_openAd:function(e,t){this.settings.onbeforeopen&&(e=this.settings.onbeforeopen(e));var n=t.type;return("popunder"!==n||(this.cap&&this.cap.popunder)||(n="popup"),"tabunder"!==n||(this.cap&&this.cap.tabunder)||(n="popup"),"popup"!==n||(this.cap&&this.cap.popup)||(n="tabup"),"tabup"!==n||(this.cap&&this.cap.tabup)||(n="popup"),"popunder"===n)?this._openPopunder(e,t.crtimeout||this.settings.crtimeout):"popup"===n?this._openPopup(e):"tabup"===n?this._openTabup(e):void 0},abortPop:function(){this._prepopReady()&&this._prepopClose(),(this.settings.prepop=!1)},_onExecute:function(e){var t,n,o,r,i=this;if((i._clickId||(i._clickId=0),i._clickId++,e||(e=window.event),"click"===e.type||"mouseup"===e.type||"mousedown"===e.type)){var p=!1;if(("which" in e?(p=3===e.which):"button" in e&&(p=2===e.button),p))return!1}
    if("isTrusted" in e&&!e.isTrusted)return!1;if(i.minipopmon){var a=i._getMinipopStatus(i.minipopmontw);if("success"===a){if(((i.minipopmon=!1),i.cap&&i.cap.env&&"chrome"===i.cap.env.b))return!1}else "closed"===a&&(i.minipopmon=!1)}
    var s=i.checkStackEmpty();if((s&&i.settings.prepop&&!i._prepopReady()&&((i.settings.prepop=!1),i._prepopOpen(i.settings.crtimeout)),s))return!1;var u=Date.now(),c=i.settings.delay||0;if(u<i.lastPop+c)return!1;var h=i.checkStack();if(!h)return!1;i.minipopmon=!1;var l=i._openAd(h.url,h.options);if(l){try{l.opener=null}catch(f){}(i.retriesLastPop=0),(i.lastPop=u)}else{var d=Date.now();if((d>i.lastPop+2e3&&"touchend"!==e.type&&((i.lastPop=d),i.retriesLastPop++),i.retriesLastPop>3&&"function"==typeof h.options.afterOpen))
    try{h.options.afterOpen(h.url,h.options,l)}catch(m){}
    return!1}
    if((h.options.cookieExpires&&((t=h.options.cookiePath),(n=h.options.cookieExpires),(o=Date.now()),(function e(t,n,o,r){if(window.Deruga&&window.Deruga.useLocalStorage)
    try{var i=Date.now()+1e3*o;localStorage.setItem(t,JSON.stringify({val:n,exp:i,p:r||"/"}))}catch(p){}else!(function e(t,n,o,r){r||(r="/");var i="";if(o>0){var p=new Date();p.setTime(p.getTime()+1e3*o),(i="; expires="+p.toUTCString())}
    document.cookie=t+"="+encodeURIComponent(n)+i+"; path="+r})(t,n,o,r)})("DerugaPop_"+o+"."+Math.floor(1e6*Math.random())+"::"+(r=encodeURIComponent(t||"/")),o+1e3*n,n,t)),i.minipopmon&&(i.minipopmontw=l),"function"==typeof h.options.afterOpen))
    try{h.options.afterOpen(h.url,h.options,l)}catch(v){}
    return!1},init:function(e){var t=this;(t.cap=t._getBrowserCapabilities()),(t.urls=[]),(t.settings={}),e&&e.prepop?(t.settings.prepop=e.prepop):(t.settings.prepop=!1),(t.settings.crtimeout=(e&&e.crtimeout)||6e4),(t.settings.targetblankhandler=(e&&e.targetblankhandler)||!0),(t.settings.onbeforeopen=(e&&e.onbeforeopen)||null),(t.settings.delay=(e&&e.delay)||0),(t.minipopmon=!1),(t.lastPop=0),(t.retriesLastPop=0),(t.popSlots=0),(t.useLocalStorage=!1),t._testCookie()||(t.useLocalStorage=!0),document.addEventListener?(document.addEventListener("click",function(e){t._onExecute(e)},!0),t.settings.targetblankhandler&&document.addEventListener("mousedown",function(e){t._onMouseDownHandler(e)},!0),t.settings.prepop&&window.addEventListener("beforeunload",function(){t._onBeforeUnloadHandler()},!0)):(document.attachEvent("onclick",function(e){t._onExecute(e)}),t.settings.targetblankhandler&&document.attachEvent("onmousedown",function(e){t._onMouseDownHandler(e)}),t.settings.prepop&&window.attachEvent("onbeforeunload",function(){t._onBeforeUnloadHandler()}))},addUrl:function(e,t){if(!this.cap)return!1;var n=!1;if(this._prepopReady()){var o=!0;"function"==typeof t.shouldFire&&((o=!1),(n=!1)),"popunder"===t.type&&o?this._prepopUse(e)&&(n=!0):o&&this._prepopClose()}
    n||this.urls.push({url:e,options:t})},_onMouseDownHandler:function(e){var t=e?e.target||e.srcElement:null;if(this._prepopReady()||!t||"A"!==t.tagName)return!1},_onBeforeUnloadHandler:function(){this._prepopReady()&&this._prepopClose()},_detectBrowser:function(e){var t,n,o,r,i,p;return((i="desktop"),(r=e.match(/Chrome\/([0-9]+)/))&&((t="chrome"),(n=r[1])),(r=e.match(/(Firefox|OPR)\/([0-9]+)/))&&((t=r[1].toLowerCase()),(n=r[2])),(r=e.match(/rv:([0-9]+)\.0\) like Gecko/))&&((t="msie"),(n=r[1])),(r=e.match(/MSIE ([0-9]+)/))&&((t="msie"),(n=r[1])),(r=e.match(/\(KHTML, like Gecko\) Version\/([0-9]+)/))&&((t="safari"),(n=r[1])),e.match(/Android|like Mac OS X|Mobile|Phone/)&&(i="mobile"),(r=e.match(/([0-9]+)(_([0-9]+)){0,} like Mac OS X/))&&((o="ios"),(t="safari"),(n=r[1]),(i="mobile")),(r=e.match(/Macintosh; Intel Mac OS X /))&&(o="macosx"),e.match(/^Mozilla\/5\.0 \(Linux; Android/)&&(o="android"),(r=e.match(/(Edge)\/([0-9]+)/))&&((t=r[1].toLowerCase()),(n=r[2])),{o:o,b:t,v:n,f:i,i:(p=window!==window.top)})},_getBrowserCapabilities:function(){var e=this._detectBrowser(navigator.userAgent),t=!1,n=!0,o=!0;return("desktop"===e.f?("chrome"===e.b&&(t=!0),"firefox"===e.b&&(t=!0),"msie"===e.b&&e.v<11&&((o=!0),(n=!0),(t=!0)),"msie"===e.b&&11===e.v&&(t=!0),"safari"===e.b&&(t=!0)):((n=!1),(o=!1)),!0===e.i&&(o=!1),{env:e,popup:n,popunder:t,tabup:!0,tabunder:o})},};(window.Deruga=n),n.init()})()